from .solo_node import solo_node_zx_graph, solo_node_block_graph
from .logical_cnot import logical_cnot_zx_graph, logical_cnot_block_graph
from .three_cnots import three_cnots_zx_graph, three_cnots_block_graph
